import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/MSG"
  UPDATE_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/UPDATE"
  ALERT_TOPIC = "NWS/CRH/BIS/COOP/MFTN8/ALERT"
  clientID = "MFTN8"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
