import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/COMMAND"
  TEMP_PUB_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/TEMP"
  PRECIP_PUB_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/PRECIP"
  DAILY_PUB_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/DAILY"
  MESSAGE_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/MSG"
  UPDATE_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/UPDATE"
  ALERT_TOPIC = "NWS/HQ/OBS/COOP/SFSC1/ALERT"
  clientID = "SFSC1"
  clientTZ = "-5"
  server_Address = "sftp.crh.noaa.gov"
