import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/MSG"
  UPDATE_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/UPDATE"
  ALERT_TOPIC = "NWS/CRH/ARX/COOP/MEDW3/ALERT"
  clientID = "MEDW3"
  clientTZ = "-6"
  atOb_T = "7"
  server_Address = "sftp.crh.noaa.gov"
