import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/#"
  COMMAND_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/MSG"
  UPDATE_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/UPDATE"
  ALERT_TOPIC = "NWS/CRH/TOP/COOP/KUSK1/ALERT"
  clientID = "KUSK1"
  clientTZ = "-6"
  atOb_T = "7"
  server_Address = "sftp.crh.noaa.gov"
