import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/MSG"
  UPDATE_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/UPDATE"
  ALERT_TOPIC = "NWS/CRH/ABR/COOP/CBAS2/ALERT"
  clientID = "CBAS2"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
