import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/MSG"
  UPDATE_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/UPDATE"
  ALERT_TOPIC = "NWS/CRH/ABR/COOP/CBAS1/ALERT"
  clientID = "CBAS1"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
