import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/#"
  COMMAND_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/MSG"
  UPDATE_TOPIC = "NWS/CRH/NRC/COOP/NRCC01/UPDATE"
  ALERT_TOPIC = "NWS/CRH/NRC/COOP/NRCC01UPDATE"
  clientID = "NRCC01"
  clientTZ = "-6"
  atOb_T = "7"
  server_Address = "sftp.crh.noaa.gov"
