import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/GJT/COOP/THMU1/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/GJT/COOP/THMU1/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/GJT/COOP/THMU1/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/GJT/COOP/THMU1/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/GJT/COOP/THMU1/MSG"
  UPDATE_TOPIC = "NWS/CRH/GJT/COOP/THMU1/UPDATE"
  ALERT_TOPIC = "NWS/CRH/GJT/COOP/THMU1/ALERT"
  clientID = "THMU1"
  clientTZ = "-7"
  server_Address = "sftp.crh.noaa.gov"
