import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/TOP/COOP/LARK1/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/TOP/COOP/LARK1/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/TOP/COOP/LARK1/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/TOP/COOP/LARK1/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/TOP/COOP/LARK1/MSG"
  UPDATE_TOPIC = "NWS/CRH/TOP/COOP/LARK1/UPDATE"
  ALERT_TOPIC = "NWS/CRH/TOP/COOP/LARK1/ALERT"
  clientID = "LARK1"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
