import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/#"
  COMMAND_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/MSG"
  UPDATE_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/UPDATE"
  ALERT_TOPIC = "NWS/CRH/LSX/COOP/PEYI2/UPDATE"
  clientID = "PEYI2"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
