import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/MSG"
  UPDATE_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/UPDATE"
  ALERT_TOPIC = "NWS/CRH/FGF/COOP/RDLM5/ALERT"
  clientID = "RDLM5"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
