import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/MSG"
  UPDATE_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/UPDATE"
  ALERT_TOPIC = "NWS/CRH/ABR/COOP/GTTS2/ALERT"
  clientID = "GTTS2"
  clientTZ = "-6"
  atOb_T = "7" #atOb Time (Hr)
  server_Address = "sftp.crh.noaa.gov"
