import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/MSG"
  UPDATE_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/UPDATE"
  ALERT_TOPIC = "NWS/CRH/DLH/COOP/WLKM5/ALERT"
  clientID = "WLKM5"
  clientTZ = "-6"
  server_Address = "sftp.crh.noaa.gov"
