import time
import sys

class pubTopic:
  #-----topics
  
  SUB_TOPIC = "NWS/ALL/ALL/COOP/ALL/COMMAND"
  COMMAND_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/COMMAND"
  TEMP_PUB_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/TEMP"
  PRECIP_PUB_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/PRECIP"
  DAILY_PUB_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/DAILY"
  MESSAGE_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/MSG"
  UPDATE_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/UPDATE"
  ALERT_TOPIC = "NWS/CRH/GRR/COOP/ALMM4/ALERT"
  clientID = "ALMM4"
  clientTZ = "-5"
  server_Address = "sftp.crh.noaa.gov"
